project:
  type: book
  output-dir: docs

bibliography: bibliog.bib
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
lang: pt-BR

book:
  page-navigation: true
  reader-mode: true
  cover-image: hardcover.png
  favicon: hardcover.png
  title: "Planejamento e Análise de Experimentos"
  author: "Ben Dêivide O. Batista"
  date: today
  page-footer:
    left: |
      Planejamento e Análise de Experimentos foi escrito por <a href="https://bendeivide.github.io/">Ben Dêivide</a></a> 
    right: |
      Este livro foi desenvolvido com o <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - cap00.qmd
    - cap01.qmd
    - cap02.qmd
    - tabelas.qmd
    - references.qmd
#https://quarto.org/docs/reference/metadata/crossref.html#custom
crossref:
  lst-title: Código R
  lst-prefix: Código R
  custom:
    - kind: float
      caption-location: top
      reference-prefix: "Tabela A"
      key: tab
  eq-prefix: ""
  
# crossref:
#   custom:
#     - kind: float
#       reference-prefix: Video
#       key: vid
#       latex-env: video
# Baseado em:
# - https://stackoverflow.com/questions/73288264/shared-counter-in-quarto-for-exercises-examples-etc
# - https://github.com/ute/custom-numbered-blocks
filters: 
  - custom-numbered-blocks
custom-numbered-blocks:
  groups: 
    exgrp: 
      collapse: false
      boxstyle: foldbox.simple #só existe essa opcao por enquanto
    thmlike:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    collike:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    todos: default
    deflike: 
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    exlike: 
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    exerlike: 
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
  classes:
    Example:
      #colors: [948bde, 584eab]
      group: exlike
      collapse: false
      label: Exemplo
    Definition:
      group: deflike
      collapse: false
      colors: [5e737f, 49606d]
      listin: [stilltodo]
      label: Definição
    Exercise:
      colors: [4485f6, 479bd1]
      collapse: false
      group: exerlike
      label: Exercício
      #listin: [listexerc]
    Theorem:
      colors: [d14747, 8b1f1f]
      group: thmlike
      label: Teorema
    Corolary:
      colors: [df6d0d, b85604]
      group: collike
      label: Corolário
    Proof:
      numbered: false
      colors: [aaa6a3, ]
      collapse: true
      boxstyle: foldbox.simple
      label: Prova
    TODO:
      label: "To do"
      colors: [e7b1b4, 8c3236]
      group: todos
      listin: [stilltodo]
    Solution:
      numbered: false
      colors: [9ad5f6, ]
      collapse: true
      boxstyle: foldbox.simple
      label: Solução  




nocite: |
  @st1980, @banzato2006, @barbin2003, @bolfarine2010, @bolfarinebussab2005,
  @cochrancox2005, @crespo2009, @dantas2008, @drapersmith1998, @magalhaeslima2023,
  @magalhaes2011, @meyer2000, @montgomery2021, @montgomery2019, @mood1974,
  @pagano2004, @pimentelgomes2022, @silva2015, @souza1998

format:
  html:
    # Profundidade das subsecoes
    number-depth: 6
    theme: cosmo
 
 



